name: ech_workers
description: ECH Workers Proxy Client for Android
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.0.0
  url_launcher: ^6.2.5
  dio: ^5.4.3+1
  flutter_svg: ^2.0.9
  package_info_plus: ^8.0.0
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.4
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  flutter_slidable: ^3.0.1
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.2.0
  equatable: ^2.0.5
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/ip_lists/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic